### ISSUE TITLE
migrate CI to GH actions

### ISSUE THREAD

**Issue by michaelkirk** [georust/geohash#40]
I noticed you still have a .travis.yml file. I believe free CI on travis-ci.org has been canceled since about June. Also, travis-ci recently had a [nasty bug (and a not great response to said bug)](https://twitter.com/peter_szilagyi/status/1437646118700175360).

Almost all of the other georust projects are running on GH actions, would you be interested in migrating? 

I could help with this if you have questions or lack the time.

**Comment by sunng87** [comment]
Thank you! Help is welcomed. We'd better use same setup for github actions across georust projects.
