### ISSUE TITLE
Compiling geohash v0.12.0 error[E0106]: missing lifetime specifier

### ISSUE THREAD

**Issue by gvasquez95** [georust/geohash#43]
When cross-building in OSX to linux-musl:

`  --> /cargo/registry/src/github.com-1ecc6299db9ec823/geohash-0.12.0/src/core.rs:88:57
   |
88 | pub fn encode(c: Coordinate<f64>, len: usize) -> Result<&String, GeohashError> {
   |                                                         ^ expected named lifetime parameter
   |
   = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
help: consider using the `'static` lifetime
   |
88 | pub fn encode(c: Coordinate<f64>, len: usize) -> Result<&'static String, GeohashError> {
   |                                                         ~~~~~~~~
`

CMD: `cross build --target aarch64-unknown-linux-musl`

rustc 1.59.0 (9d1b2106e 2022-02-23)

**Comment by gvasquez95** [comment]
it happens when building `release` distros, even on mac osx

**Comment by gvasquez95** [comment]
this is odd....the src file got corrupted...deleted the local cache and the fresh copy works 🤔

**Comment by lnicola** [comment]
It's pretty easy to edit the files in the cargo cache. We can probably close this.

**Comment by michaelkirk** [comment]
Seems like this was a problem just with the local dev setup, so I'm going to close. Feel free to clarify if you understand things differently @gvasquez95.
