### ISSUE TITLE
edge of hashes

### ISSUE THREAD

**Issue by jceaser** [georust/geohash#54]
Can you add a test for latitude 0.0 and longitude -180.0 and other such edges? You return 80000, which I think is correct but is not what tools like https://www.geohash.es/encode or https://github.com/wdm0006/pygeohash return. They return 2pbpbpb which looks like a rounding error. Since you have a spread sheet for these tests, I think you should add the official results for these locations. At least then I know where you officially stand on this issue.

**Comment by sunng87** [comment]
@jceaser I just added this case in #55
